### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by willfurnell** [shimt/pam-exec-oauth2#5]
Hey! This looks really cool :) 

Do you have any documentation on using this with a generic OAuth2 provider not just Azure AD? What type of authentication flow is this using, and what scopes do I need to give this client etc? please?

Thanks!

**Comment by Glowsome** [comment]
@willfurnell
i am using this with a NetIQ (now called Microfocus) AccessManager and works fine.
Still fiddling around, but this gives successfull authentication : 
`{
    client-id: "<your Client-ID>",
    client-secret: "<your Client Secret>",
    redirect-url: "urn:ietf:wg:oauth:2.0:oob",
    scopes: ["email"],
    endpoint-auth-url: "https://<your AccessManager>/nidp/oauth/nam/authz",
    endpoint-token-url: "https://<your AccessManager>/nidp/oauth/nam/token",
    extra-parameters: {
        acr: "saml/secure/form/password/smartphone"
    },
    username-format: "%s",
}
`
As you can see i have adapted the 'extra-parameter' to request a specific authentication contract from my box.
If you were to remove it it will authenticate you with the default authentication contract.

**Comment by alerque** [comment]
As another data point that could be documented, here is a working config file using this PAM module to connect to a Keycloak server:

```yaml
{
   client-id: pam,
   client-secret: <REDACTED>,
   scopes: ["profile"],
   endpoint-token-url: "https://keycloak.example.com/auth/realms/<REALM_NAME>/protocol/openid-connect/token",
   extra-parameters: {
   },
}
```

This uses a custom client setup on the Keycloak end called "pam" with settings that look like this:

![image](https://user-images.githubusercontent.com/173595/116776669-60164d00-aa72-11eb-895d-9fe7d4206a96.png)
